modLoader="javafml"
loaderVersion="[40,)"
license="GNU GPLv3"
#issueTrackerURL="https://github.com/we-commit-coding-felonies/magitekkittweaks/issues"

[[mods]]
modId="magitekkit"
version="${file.jarVersion}"
displayName="MagiTekkit Tweaks"
displayURL="https://github.com/we-commit-coding-felonies/magitekkittweaks"
# https://mcforge.readthedocs.io/en/latest/gettingstarted/autoupdate/
#updateJSONURL="https://github.com/we-commit-coding-felonies/magitekkittweaks"
logoFile="logo.png"
authors="solunareclipse1"
credits="ProjectE, Botania"
description='''
Custom code mod for the MagiTekkit modpack
'''
[[dependencies.magitekkit]]
    modId="forge"
    mandatory=true
    versionRange="[40,41)"
    ordering="NONE"
    side="BOTH"
[[dependencies.magitekkit]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18.2,1.19)"
    ordering="NONE"
    side="BOTH"
[[dependencies.magitekkit]]
	modId="projecte"
	mandatory=true
	versionRange="*"
	ordering="BEFORE"
	side="BOTH"
[[dependencies.magitekkit]]
	modId="botania"
	mandatory=true
	versionRange="*"
	ordering="BEFORE"
[[dependencies.magitekkit]]
	modId="avaritia"
	mandatory=true
	versionRange="*"
	ordering="BEFORE"
	side="BOTH"